In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('/content/imdb-top-1000.csv')

In [3]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [4]:
genres = movies.groupby('Genre')

In [5]:
genres.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [6]:
genres.mean(numeric_only=True)

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [7]:
genres.std(numeric_only=True)

             Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     28.500706     0.304258  432946.814748  2.256724e+08  12.421252
Adventure  33.317320     0.229781  301188.347642  1.697543e+08  12.345393
Animation  14.530471     0.253221  262173.231571  2.091840e+08   8.813646
Biography  25.514466     0.267140  271284.191372  1.363251e+08  11.028187
Comedy     22.946213     0.228771  188653.570564  1.946513e+08  11.829160
Crime      27.689231     0.335477  373999.730656  1.571191e+08  13.099102
Drama      27.740490     0.267229  305554.162841  2.201164e+08  12.744687
Family     10.606602     0.000000  137008.302816  3.048412e+08  16.970563
Fantasy    12.727922     0.141421   22179.111299  7.606861e+07        NaN
Film-Noir   4.000000     0.152753   54649.083277  7.048472e+07   1.527525
Horror     13.604812     0.311302  234883.508691  9.965017e+07  15.362291
Mystery    14.475423     0.310791  404621.915297  1.567524e+08  18.604435
Thriller         NaN          NaN            NaN           NaN        NaN
Western    17.153717     0.420317  263489.554280  1.230626e+07   9.032349

In [8]:
genres.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [9]:
genres.mean(numeric_only=True)

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [10]:
movies.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [11]:
print(genres.mean(numeric_only=True))

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [12]:
genres['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [13]:
genres['IMDB_Rating'].mean().sort_values(ascending=False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64

In [14]:
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [15]:
genres['IMDB_Rating'].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [16]:
movies['Star1'].value_counts()

Star1
Tom Hanks          12
Robert De Niro     11
Al Pacino          10
Clint Eastwood     10
Humphrey Bogart     9
                   ..
Preity Zinta        1
Javier Bardem       1
Ki-duk Kim          1
Vladimir Garin      1
Robert Donat        1
Name: count, Length: 660, dtype: int64

In [17]:
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64

In [18]:
movies.groupby('Star1')['Series_Title'].count()

Star1
Aamir Khan              7
Aaron Taylor-Johnson    1
Abhay Deol              1
Abraham Attah           1
Adam Driver             1
                       ..
Zbigniew Zamachowski    1
Zooey Deschanel         1
Çetin Tekindor          1
Éric Toledano           1
Ömer Faruk Sorak        1
Name: Series_Title, Length: 660, dtype: int64

In [19]:
len(movies.groupby('Genre'))

14

In [20]:
movies['Genre'].nunique()

14

In [21]:
movies.groupby('Genre').size().sort_values(ascending=False)

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Family         2
Fantasy        2
Thriller       1
dtype: int64

In [22]:
movies['Genre'].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [23]:
genres = movies.groupby('Genre')
genres.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [24]:
genres.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [25]:
genres.nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [26]:
genres.get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [27]:
genres.get_group('Fantasy')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [28]:
genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [29]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [30]:
genres.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
718,Scarface: The Shame of the Nation,1932,93,Action,7.8,Howard Hawks,Richard Rosson,25312,82900837.0,87.0
502,Iron Man,2008,126,Action,7.9,Jon Favreau,Robert Downey Jr.,939644,318412101.0,79.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
686,The Right Stuff,1983,193,Adventure,7.8,Philip Kaufman,Sam Shepard,56235,21500000.0,91.0
771,Tangled,2010,100,Animation,7.7,Nathan Greno,Byron Howard,405922,200821936.0,71.0
367,Ratatouille,2007,111,Animation,8.0,Brad Bird,Jan Pinkava,641645,206445654.0,96.0
810,Shine,1996,105,Biography,7.7,Scott Hicks,Geoffrey Rush,51350,35811509.0,87.0
587,Pride,2014,119,Biography,7.8,Matthew Warchus,Bill Nighy,51841,574305769.0,79.0
679,Ferris Bueller's Day Off,1986,103,Comedy,7.8,John Hughes,Matthew Broderick,321382,70136369.0,61.0
435,La dolce vita,1960,174,Comedy,8.0,Federico Fellini,Marcello Mastroianni,66621,19516000.0,95.0
79,Witness for the Prosecution,1957,116,Crime,8.4,Billy Wilder,Tyrone Power,108862,8175000.0,NaN
474,Nightcrawler,2014,117,Crime,7.9,Dan Gilroy,Jake Gyllenhaal,466134,32381218.0,76.0
443,La Strada,1954,108,Drama,8.0,Federico Fellini,Anthony Quinn,58314,101832153.0,NaN
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
961,Lost Highway,1997,134,Mystery,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

In [31]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [32]:
genres = movies.groupby('Genre')

In [33]:
genres.sum(numeric_only=True)

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [34]:
genres.agg({
    'Runtime':'mean',
    'IMDB_Rating':'mean',
    'No_of_Votes':'sum',
    'Gross':'sum',
    'Metascore':'min'
})

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [35]:
genres.agg(['min','max','sum'])

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                                \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                                             Released_Year  \
                                                         sum           min
Genre
Action     The Dark KnightThe Lord of the Rings: The Retu...          1924
Adventure  InterstellarBack to the FutureInglourious Bast...          1925
Animation  Sen to Chihiro no kamikakushiThe Lion KingHota...          1940
Biography  Schindler's ListGoodfellasHamiltonThe Intoucha...          1928
Comedy     GisaengchungLa vita è bellaModern TimesCity Li...          1921
Crime      The GodfatherThe Godfather: Part II12 Angry Me...          1931
Drama      The Shawshank RedemptionFight ClubForrest Gump...          1925
Family     E.T. the Extra-TerrestrialWilly Wonka & the Ch...          1971
Fantasy                Das Cabinet des Dr. CaligariNosferatu          1920
Film-Noir   The Third ManThe Maltese FalconShadow of a Doubt          1941
Horror     PsychoAlienThe ThingThe ExorcistNight of the L...          1933
Mystery    MementoRear WindowVertigoShutter IslandKahaani...          1938
Thriller                                     Wait Until Dark          1967
Western    Il buono, il brutto, il cattivoOnce Upon a Tim...          1965

                                                                   Runtime  \
            max                                                sum     min
Genre
Action     2019  2008200320102001200219991980197719621954200019...      45
Adventure    PG  2014198520091981196819621959201319751963194819...      88
Animation  2020  2001199419882016201820172008199719952019200920...      71
Biography  2020  1993199020202011200220171995198420182013201320...      93
Comedy     2020  2019199719361931200919641940200120001973196019...      68
Crime      2019  1972197419571994200219991995199120192006199519...      80
Drama      2020  1994199919941975202019981946201420061998198819...      64
Family     1982                                           19821971     100
Fantasy    1922                                           19201922      76
Film-Noir  1949                                       194919411943     100
Horror     2017       19601979198219731968196120171978193320042001      71
Mystery    2012   200019541958201020121995197219381988201219981997      96
Thriller   1967                                               1967     108
Western    1976                                   1966196819651976     132

                      IMDB_Rating  ...  \
           max    sum         min  ...
Genre                              ...
Action     321  22196         7.6  ...
Adventure  228   9656         7.6  ...
Animation  137   8166         7.6  ...
Biography  209  11970         7.6  ...
Comedy     188  17380         7.6  ...
Crime      229  13524         7.6  ...
Drama      242  36049         7.6  ...
Family     115    215         7.8  ...
Fantasy     94    170         7.9  ...
Film-Noir  108    312         7.8  ...
Horror     122   1123         7.6  ...
Mystery    138   1429         7.6  ...
Thriller   108    108         7.8  ...
Western    165    593         7.8  ...

                                                       Star1 No_of_Votes  \
                                                         sum         min
Genre
Action     Christian BaleElijah WoodLeonardo DiCaprioElij...       25312
Adventure  Matthew McConaugheyMichael J. FoxBrad PittJürg...       29999
Animation  Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...       25229
Biography  Liam NeesonRobert De NiroLin-Manuel MirandaÉri...       27254
Comedy     Kang-ho SongRoberto BenigniCharles ChaplinChar...       26337
Crime      Marlon BrandoAl PacinoHenry FondaJohn Travolta...       27712
Drama      Tim RobbinsBrad PittTom HanksJack NicholsonSur...       25088
Family                               Henry ThomasGene Wilder      178731
Fantasy                             Werner KraussMax Schreck       57428
Film-Noir           Orson WellesHumphrey BogartTeresa Wright       59556
Horror     Anthony PerkinsSigourney WeaverKurt RussellEll...       27007
Mystery    Guy PearceJames StewartJames StewartLeonardo D...       33982
Thriller                                      Audrey Hepburn       27733
Western    Clint EastwoodHenry FondaClint EastwoodClint E...       65659

                                    Gross                             \
               max       sum          min          max           sum
Genre
Action     2303232  72282412       3296.0  936662225.0  3.263226e+10
Adventure  1512360  22576163      61001.0  874211619.0  9.496922e+09
Animation   999790  21978630     128985.0  873839108.0  1.463147e+10
Biography  1213505  24006844      21877.0  753585104.0  8.276358e+09
Comedy      939631  27620327       1305.0  886752933.0  1.566387e+10
Crime      1826188  33533615       6013.0  790482117.0  8.452632e+09
Drama      2343110  61367304       3600.0  924558264.0  3.540997e+10
Family      372490    551221    4000000.0  435110554.0  4.391106e+08
Fantasy      88794    146222  337574718.0  445151978.0  7.827267e+08
Film-Noir   158731    367215     449191.0  123353292.0  1.259105e+08
Horror      787806   3742556      89029.0  298791505.0  1.034649e+09
Mystery    1129894   4203004    1035953.0  474203697.0  1.256417e+09
Thriller     27733     27733   17550741.0   17550741.0  1.755074e+07
Western     688390   1289665    5321508.0   31800000.0  5.822151e+07

          Metascore
                min    max      sum
Genre
Action         33.0   98.0  10499.0
Adventure      41.0  100.0   5020.0
Animation      61.0   96.0   6082.0
Biography      48.0   97.0   6023.0
Comedy         45.0   99.0   9840.0
Crime          47.0  100.0   6706.0
Drama          28.0  100.0  19208.0
Family         67.0   91.0    158.0
Fantasy         NaN    NaN      0.0
Film-Noir      94.0   97.0    287.0
Horror         46.0   97.0    880.0
Mystery        52.0  100.0    633.0
Thriller       81.0   81.0     81.0
Western        69.0   90.0    313.0

[14 rows x 27 columns]

In [36]:
genres.agg({
    'Runtime':['min','mean'],
    'IMDB_Rating':'mean',
    'No_of_Votes':['sum','max'],
    'Gross':'sum',
    'Metascore':'min'
})

          Runtime             IMDB_Rating No_of_Votes                  Gross  \
              min        mean        mean         sum      max           sum
Genre
Action         45  129.046512    7.949419    72282412  2303232  3.263226e+10
Adventure      88  134.111111    7.937500    22576163  1512360  9.496922e+09
Animation      71   99.585366    7.930488    21978630   999790  1.463147e+10
Biography      93  136.022727    7.938636    24006844  1213505  8.276358e+09
Comedy         68  112.129032    7.901290    27620327   939631  1.566387e+10
Crime          80  126.392523    8.016822    33533615  1826188  8.452632e+09
Drama          64  124.737024    7.957439    61367304  2343110  3.540997e+10
Family        100  107.500000    7.800000      551221   372490  4.391106e+08
Fantasy        76   85.000000    8.000000      146222    88794  7.827267e+08
Film-Noir     100  104.000000    7.966667      367215   158731  1.259105e+08
Horror         71  102.090909    7.909091     3742556   787806  1.034649e+09
Mystery        96  119.083333    7.975000     4203004  1129894  1.256417e+09
Thriller      108  108.000000    7.800000       27733    27733  1.755074e+07
Western       132  148.250000    8.350000     1289665   688390  5.822151e+07

          Metascore
                min
Genre
Action         33.0
Adventure      41.0
Animation      61.0
Biography      48.0
Comedy         45.0
Crime          47.0
Drama          28.0
Family         67.0
Fantasy         NaN
Film-Noir      94.0
Horror         46.0
Mystery        52.0
Thriller       81.0
Western        69.0

In [37]:
genres

In [38]:
for group,data in genres:
  print(type(group),type(data))

<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>

In [39]:
for group,data in genres:
  print(data)

                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action          9.0  Christopher Nolan     Christian Bale      2303232
5    Action          8.9      Peter Jackson        Elijah Wood      1642758
8    Action          8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action          8.8      Peter Jackson        Elijah Wood      1661481
13   Action          8.7      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action          7.6    Joel Schumacher    Michael Douglas       171640
979  Action          7.6     Richard Donner         Mel Gibson       236894
982  Action          7.6      George Miller         Mel Gibson       166588
983  Action          7.6        Walter Hill       Michael Beck        93878
985  Action          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 10 columns]
                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21           8.6  Christopher Nolan  Matthew McConaughey      1512360
47           8.5    Robert Zemeckis       Michael J. Fox      1058081
93           8.3  Quentin Tarantino            Brad Pitt      1267869
110          8.3  Wolfgang Petersen      Jürgen Prochnow       231855
114          8.3    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957          7.6      Terry Gilliam          Johnny Depp       259753
964          7.6       Jim Jarmusch          Johnny Depp        90442
966          7.6         Ron Howard            Tom Hanks       269197
984          7.6      James Frawley           Jim Henson        32802
991          7.6    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21   188020017.0       74.0
47   210609762.0       87.0
93   120540719.0       69.0
110   11487676.0       86.0
114   56954992.0       84.0
..           ...        ...
957   10680275.0       41.0
964    1037847.0       62.0
966  173837933.0       77.0
984   76657000.0       74.0
991    1378435.0       50.0

[72 rows x 10 columns]
                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23           8.6       Hayao Miyazaki     Daveigh Chase       651376
43           8.5         Roger Allers       Rob Minkoff       942045
46           8.5        Isao Takahata   Tsutomu Tatsumi       235231
56           8.4       Makoto Shinkai  Ryûnosuke Kamiki       194838
58           8.4      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956          7.6        Tony Bancroft        Barry Cook       256906
971          7.6        Isao Takahata         Miki Imai        27071
976          7.6         Ron Clements       John Musker       237696
986          7.6         Martin Rosen       John Hubley        33656
992          7.6  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23    10055859.0       96.0
43   422783777.0       88.0
46   150734678.0       94.0
56     5017246.0       79.0
58   190241310.0       87.0
..           ...        ...
956  120620254.0       71.0
971     453243.0       90.0
976  111543479.0       88.0
986  232841485.0       64.0
992  141843612.0       65.0

[82 rows x 10 columns]
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography          8.9
15          Goodfellas          1990      146  Biography          8.7
18            Hamilton          2020      160  Biography          8.6
35    The Intouchables          2011      112  Biography          8.5
38         The Pianist          2002      150  Biography          8.5
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography          7.6
940  Finding Neverland          2004      106  Biography          7.6
949               Blow          2001      124  Biography          7.6
952      The Hurricane          1999      146  Biography          7.6
987   Midnight Express          1978      121  Biography          7.6

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505   96898818.0       94.0
15    Martin Scorsese      Robert De Niro      1020727   46836394.0       90.0
18        Thomas Kail  Lin-Manuel Miranda        55291  440984783.0       90.0
35    Olivier Nakache       Éric Toledano       760360   13182281.0       57.0
38     Roman Polanski        Adrien Brody       729603   32572577.0       85.0
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781   10301706.0       66.0
940      Marc Forster         Johnny Depp       198677   51680613.0       67.0
949         Ted Demme         Johnny Depp       240714   52990775.0       52.0
952    Norman Jewison   Denzel Washington        91557   50668906.0       74.0
987       Alan Parker          Brad Davis        73662   35000000.0       59.0

[88 rows x 10 columns]
                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy          8.6     Bong Joon Ho     Kang-ho Song       552778
26   Comedy          8.6  Roberto Benigni  Roberto Benigni       623629
51   Comedy          8.5  Charles Chaplin  Charles Chaplin       217881
52   Comedy          8.5  Charles Chaplin  Charles Chaplin       167839
64   Comedy          8.4  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy          7.6     David Zucker   Leslie Nielsen       152871
978  Comedy          7.6      John Hughes     Steve Martin       124773
989  Comedy          7.6    Robert Altman    Elliott Gould        26337
994  Comedy          7.6   Richard Lester      John Lennon        40351
995  Comedy          7.6    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19    53367844.0       96.0
26    57598247.0       59.0
51      163245.0       96.0
52       19181.0       99.0
64     6532908.0       67.0
..           ...        ...
977   78756177.0       76.0
978   49530280.0       72.0
989     959000.0       87.0
994   13780024.0       96.0
995  679874270.0       76.0

[155 rows x 10 columns]
                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime          9.2
3     The Godfather: Part II          1974      202  Crime          9.0
4               12 Angry Men          1957       96  Crime          9.0
6               Pulp Fiction          1994      154  Crime          8.9
22            Cidade de Deus          2002      130  Crime          8.6
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime          7.6
960                 Sleepers          1996      147  Crime          7.6
974  The Godfather: Part III          1990      162  Crime          7.6
980             Blood Simple          1984       99  Crime          7.6
999             The 39 Steps          1935       86  Crime          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 10 columns]
                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0            9.3          Frank Darabont        Tim Robbins      2343110
9            8.8           David Fincher          Brad Pitt      1854740
11           8.8         Robert Zemeckis          Tom Hanks      1809221
17           8.7            Milos Forman     Jack Nicholson       918088
20           8.6           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990          7.6            Sergio Leone        Rod Steiger        30144
993          7.6  Michelangelo Antonioni     David Hemmings        56513
996          7.6          George Stevens   Elizabeth Taylor        34075
997          7.6          Fred Zinnemann     Burt Lancaster        43374
998          7.6        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0     28341469.0       80.0
9     37030102.0       66.0
11   330252182.0       82.0
17   112000000.0       83.0
20   556832648.0        NaN
..           ...        ...
990     696690.0       77.0
993  632532802.0       82.0
996  195217415.0       84.0
997   30500000.0       85.0
998  852142728.0       78.0

[289 rows x 10 columns]
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0
568          7.9   F.W. Murnau    Max Schreck        88794  445151978.0

     Metascore
321        NaN
568        NaN
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir          8.1
456  The Maltese Falcon          1941      100  Film-Noir          8.0
712   Shadow of a Doubt          1943      108  Film-Noir          7.8

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731     449191.0       97.0
456       John Huston  Humphrey Bogart       148928    2108060.0       96.0
712  Alfred Hitchcock    Teresa Wright        59556  123353292.0       94.0
                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror          8.5
75                      Alien          1979      117  Horror          8.4
271                 The Thing          1982      109  Horror          8.1
419              The Exorcist          1973      122  Horror          8.0
544  Night of the Living Dead          1968       96  Horror          7.9
707             The Innocents          1961      100  Horror          7.8
724                   Get Out          2017      104  Horror          7.7
844                 Halloween          1978       91  Horror          7.7
876         The Invisible Man          1933       71  Horror          7.7
932                       Saw          2004      103  Horror          7.6
948                The Others          2001      101  Horror          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery          8.4
81         Rear Window          1954      112  Mystery          8.4
119            Vertigo          1958      128  Mystery          8.3
145     Shutter Island          2010      138  Mystery          8.2
220            Kahaani          2012      122  Mystery          8.1
393     Twelve Monkeys          1995      129  Mystery          8.0
420             Sleuth          1972      138  Mystery          8.0
714  The Lady Vanishes          1938       96  Mystery          7.8
829          Spoorloos          1988      107  Mystery          7.7
899          El cuerpo          2012      112  Mystery          7.6
959          Dark City          1998      100  Mystery          7.6
961       Lost Highway          1997      134  Mystery          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0
959           Alex Proyas              Rufus Sewell       187927   14378331.0
961           David Lynch              Bill Pullman       131101    3796699.0

     Metascore
69        80.0
81       100.0
119      100.0
145       63.0
220        NaN
393       74.0
420        NaN
714       98.0
829        NaN
899        NaN
959       66.0
961       52.0
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733  17550741.0       81.0

In [40]:
top = []
for group,data in genres:
  rate = (data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])
  top.append(rate)
df = pd.concat(top,ignore_index=True)

In [41]:
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
1,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
2,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
3,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
4,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
5,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
6,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
7,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
8,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
9,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
10,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
11,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
12,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
13,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
14,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
15,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
16,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [42]:
type(df)

pandas.core.frame.DataFrame

In [43]:
movies.groupby('Genre').apply(min)

<ipython-input-43-ed416e7156ea>:1: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  movies.groupby('Genre').apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [44]:
def foo(group):
  return group['Series_Title'].str.startswith('A').sum()

In [45]:
genres.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [46]:
def rank_movie(group):
  group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
  return group

In [47]:
print(genres.apply(rank_movie))

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              genre_rank
Genre
Action   2           1.0
         5           2.0
         8           3.5
         10          3.5
         13          6.0
...                  ...
Thriller 700         1.0
Western  12          1.0
         48          2.0
         115         3.0
         691         4.0

[1000 rows x 11 columns]

In [52]:
def normal(group):
  group['norm_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min())/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group

In [53]:
genres.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              norm_rating
Genre
Action   2       1.000000
         5       0.928571
         8       0.857143
         10      0.857143
         13      0.785714
...                   ...
Thriller 700          NaN
Western  12      1.000000
         48      0.700000
         115     0.500000
         691     0.000000

[1000 rows x 11 columns]

In [54]:
duo = movies.groupby(['Director','Star1'])
duo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [56]:
duo.get_group(('Abhishek Kapoor','Amit Sadh'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
735,Kai po che!,2013,130,Drama,7.7,Abhishek Kapoor,Amit Sadh,32628,1122527.0,40.0

In [60]:
duo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [69]:
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False).head(1)

              Star1  Genre  Metascore
230  Ellar Coltrane  Drama      100.0

In [73]:
duo.agg(['min','max'])

                                                  Series_Title  \
                                                           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab
Abhishek Kapoor     Amit Sadh                      Kai po che!
...                                                        ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara
                    Vijay Varma                      Gully Boy
Çagan Irmak         Çetin Tekindor              Babam ve Oglum
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.

                                                               Released_Year  \
                                                           max           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par          2007
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7          2020
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle          2013
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab          2016
Abhishek Kapoor     Amit Sadh                      Kai po che!          2013
...                                                        ...           ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid          2013
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara          2011
                    Vijay Varma                      Gully Boy          2019
Çagan Irmak         Çetin Tekindor              Babam ve Oglum          2005
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.          2004

                                         Runtime           Genre             \
                                     max     min  max        min        max
Director            Star1
Aamir Khan          Amole Gupte     2007     165  165      Drama      Drama
Aaron Sorkin        Eddie Redmayne  2020     129  129      Drama      Drama
Abdellatif Kechiche Léa Seydoux     2013     180  180      Drama      Drama
Abhishek Chaubey    Shahid Kapoor   2016     148  148     Action     Action
Abhishek Kapoor     Amit Sadh       2013     130  130      Drama      Drama
...                                  ...     ...  ...        ...        ...
Zaza Urushadze      Lembit Ulfsak   2013      87   87      Drama      Drama
Zoya Akhtar         Hrithik Roshan  2011     155  155     Comedy     Comedy
                    Vijay Varma     2019     154  154      Drama      Drama
Çagan Irmak         Çetin Tekindor  2005     112  112      Drama      Drama
Ömer Faruk Sorak    Cem Yilmaz      2004     127  127  Adventure  Adventure

                                   IMDB_Rating      No_of_Votes          \
                                           min  max         min     max
Director            Star1
Aamir Khan          Amole Gupte            8.4  8.4      168895  168895
Aaron Sorkin        Eddie Redmayne         7.8  7.8       89896   89896
Abdellatif Kechiche Léa Seydoux            7.7  7.7      138741  138741
Abhishek Chaubey    Shahid Kapoor          7.8  7.8       27175   27175
Abhishek Kapoor     Amit Sadh              7.7  7.7       32628   32628
...                                        ...  ...         ...     ...
Zaza Urushadze      Lembit Ulfsak          8.2  8.2       40382   40382
Zoya Akhtar         Hrithik Roshan         8.1  8.1       67927   67927
                    Vijay Varma            8.0  8.0       31886   31886
Çagan Irmak         Çetin Tekindor         8.3  8.3       78925   78925
Ömer Faruk Sorak    Cem Yilmaz             8.0  8.0       56960   56960

                                          Gross              Metascore
                                            min          max       min   max
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0       NaN   NaN
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0      77.0  77.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0      89.0  89.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0       NaN   NaN
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0      40.0  40.0
...                                         ...          ...       ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0      73.0  73.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0       NaN   NaN
                    Vijay Varma       5566534.0    5566534.0      65.0  65.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0       NaN   NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0       NaN   NaN

[898 rows x 16 columns]

In [76]:
ipl = pd.read_csv('/content/deliveries.csv')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [78]:
ipl.shape

(179078, 21)

In [81]:
ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [87]:
six = ipl[ipl['batsman_runs'] == 6]
six.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(10)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
V Kohli           191
DA Warner         181
SR Watson         177
KA Pollard        175
YK Pathan         161
Name: batsman, dtype: int64

In [93]:
temp_df = ipl[ipl['over'] > 15]
temp_df = temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(10)

batsman
MS Dhoni          340
AB de Villiers    208
RG Sharma         208
KA Pollard        206
V Kohli           160
YK Pathan         149
KD Karthik        145
Yuvraj Singh      130
AD Russell        129
AT Rayudu         114
Name: batsman, dtype: int64

In [98]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [113]:
def highest(batsman):
    temp_df = ipl[ipl['batsman'] == batsman]
    return temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

In [114]:
highest('CH Gayle')

175

In [115]:
highest('DA Warner')

126